openapi: 3.0.0
info:
  title: Student Management API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
            type: object
            properties:
              username: { type: string }
              password: { type: string }
              role: { type: string, enum: [admin, user] }
      responses:
        '201': { description: User registered }
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        '200': { description: Login successful, returns JWT }
  /students:
    post:
      summary: Create a student
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                studentId: { type: string }
                grade: { type: number }
                class: { type: string }
      responses:
        '201': { description: Student created }
    get:
      summary: Get all students
      security: [{ bearerAuth: [] }]
      parameters: 
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: limit
          schema: { type: integer }
        - in: query
          name: search
          schema: { type: string }
      responses:
        '200': { description: List of students }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
